<a href="https://colab.research.google.com/github/2303A52058/23CSBTB39-40/blob/main/sample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
# Create a 1D NumPy array
array1 = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array1)

# Create a 2D NumPy array (matrix)
array2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(array2)

# Basic operations
# Element-wise addition
array_sum = array1 + 10
print("\nElement-wise addition (array1 + 10):")
print(array_sum)

# Element-wise multiplication
array_product = array1 * 2
print("\nElement-wise multiplication (array1 * 2):")
print(array_product)

# Matrix multiplication
matrix_product = np.dot(array2, array2.T)  # array2.T is the transpose of array2
print("\nMatrix multiplication (array2 . array2.T):")
print(matrix_product)

# Statistical operations
mean_value = np.mean(array1)
std_deviation = np.std(array1)
print(f"\nMean of array1: {mean_value}")
print(f"Standard deviation of array1: {std_deviation}")

# Create an array of zeros
zeros_array = np.zeros((3, 3))
print("\nArray of zeros:")
print(zeros_array)

# Create an array of ones
ones_array = np.ones((2, 4))
print("\nArray of ones:")
print(ones_array)

# Reshape an array
reshaped_array = np.arange(12).reshape((3, 4))
print("\nReshaped array (3x4):")
print(reshaped_array)












1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]

Element-wise addition (array1 + 10):
[11 12 13 14 15]

Element-wise multiplication (array1 * 2):
[ 2  4  6  8 10]

Matrix multiplication (array2 . array2.T):
[[14 32]
 [32 77]]

Mean of array1: 3.0
Standard deviation of array1: 1.4142135623730951

Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Array of ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Reshaped array (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
